# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: "Linux"
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
    - task: DotNetCoreCLI@2
      displayName: "unit tests"
      inputs:
        command: test
        projects: '**/*Test/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: "dotnet publish for linux-x64"
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: './taa/taa.csproj'
        arguments: '-c Release -f linux-x64 --self-contained true --output $(Build.ArtifactStagingDirectory)'
    